version: "3"
services:
  flask_app:
    container_name: flask_app_container
    build: .
    command: python run.py
    environment:
    - SECRET_KEY=MySecretKey
    - SQLALCHEMY_DATABASE_URI=MyDatabaseURI
    - EMAIL_USER=MyEmailUsername
    - EMAIL_PASS=MyEmailPassword
    ports:
      - "5000:5000"
    volumes:
      - .:/python-flask
    networks:
      flask_network:
        ipv4_address: 172.20.0.2
networks:
  flask_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24