version: "3"
services:
  flask_app:
    container_name: flask_app_container
    restart: always
    build: .
    command: gunicorn --env SCRIPT_NAME=/flaskblog -w 1 run:app -b 0.0.0.0
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/python-flask
    networks:
      flask_network:
        ipv4_address: 172.21.0.2

networks:
  flask_network:
    ipam:
      config:
        - subnet: 172.21.0.0/24
